### ISSUE TITLE
建议ayu_mirage和ayu_dark的的theme

### ISSUE THREAD

**Issue by leoatchina** [sainnhe/lightline_foobar.vim#1]
ayu_light我使用过，但是在深色主题下和ayu mirage/dark配合不好看，暂时用screry_alter。
感谢UP主的工作。

**Comment by sainnhe** [comment]
这个仓库只是为了满足我个人的需求才开的，我个人只觉得ayu light比较好看，对dark和mirage暂时不太感冒，所以不太想配这两个。
你要是有这方面的需求的话可以自己配，欢迎PR
